variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: "ci_test"

cleantest_job:
    image: javanlabs/gitlab-ci-php70:latest
    script:
        - composer install --no-progress --prefer-dist --no-scripts
        - ./vendor/bin/phpcs --standard=PSR2 app/

unittest_job:
    image: javanlabs/gitlab-ci-php70:latest
    services:
        - mysql:5.7
    script:
        - composer install --no-progress --prefer-dist --no-scripts
        - echo "APP_ENV=testing" >> .env
        - echo "APP_KEY=" >> .env
        - echo "DB_CONNECTION_TEST=mysql_test" >> .env
        - echo "DB_HOST_TEST=mysql" >> .env
        - echo "DB_DATABASE_TEST=ci_test" >> .env
        - echo "DB_USERNAME_TEST=root" >> .env
        - echo "DB_PASSWORD_TEST=" >> .env
        - touch database/database.sqlite
        - php artisan key:generate
        - php artisan migrate:refresh --seed --database=mysql_testing
        - ./vendor/bin/phpunit